from __future__ import annotations

from typing import Any

GROUPS: list[dict[str, str]] = [
    {"key": "paths", "label_en": "Paths", "label_zh": "基础路径"},
    {"key": "retrieval", "label_en": "Retrieval", "label_zh": "召回参数"},
    {"key": "vector_embedding", "label_en": "Vector & embedding", "label_zh": "向量与 embedding"},
    {"key": "claims", "label_en": "Structured claims", "label_zh": "结构化 claims"},
    {"key": "workspace", "label_en": "Workspace isolation", "label_zh": "工作区隔离"},
    {"key": "split", "label_en": "Long-content split", "label_zh": "长文分段"},
    {"key": "update", "label_en": "Update check", "label_zh": "更新检查"},
    {"key": "client_identity", "label_en": "Client identity", "label_zh": "客户端身份"},
]

CONFIG_DESCRIPTORS: list[dict[str, Any]] = [
    {
        "path": "db_path",
        "type": "path",
        "default": "./memory_arbiter.sqlite3",
        "env": "MEMORY_ARBITER_DB_PATH",
        "group": "paths",
        "label_en": "Database path",
        "label_zh": "数据库路径",
        "desc_en": "SQLite database that stores memories, conflicts, claims, and history.",
        "desc_zh": "存储记忆、冲突、claims 和历史版本的 SQLite 数据库。",
        "risk": "high",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "backup_jsonl",
        "type": "path",
        "default": "./memory_arbiter.backup.jsonl",
        "env": "MEMORY_ARBITER_BACKUP_JSONL",
        "group": "paths",
        "label_en": "Backup JSONL path",
        "label_zh": "JSONL 备份路径",
        "desc_en": "Append-only fallback backup used when SQLite is unavailable.",
        "desc_zh": "SQLite 不可用时使用的追加式兜底备份文件。",
        "risk": "high",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "policy_path",
        "type": "path",
        "default": None,
        "env": "MEMORY_ARBITER_POLICY",
        "group": "paths",
        "label_en": "Policy path",
        "label_zh": "策略文件路径",
        "desc_en": "Optional policy file for client and agent enablement.",
        "desc_zh": "可选的客户端和 agent 启用策略文件。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "recall_pool_cap",
        "type": "int",
        "default": 50,
        "env": "MEMORY_ARBITER_RECALL_POOL_CAP",
        "group": "retrieval",
        "label_en": "Recall pool size",
        "label_zh": "召回候选池大小",
        "desc_en": "Raise when the store grows so relevant memories do not miss the candidate pool.",
        "desc_zh": "记忆库变大后可适当调高，避免相关记忆进不了候选池。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "content_like_cap",
        "type": "int",
        "default": 30,
        "env": "MEMORY_ARBITER_CONTENT_LIKE_CAP",
        "group": "retrieval",
        "label_en": "Content LIKE cap",
        "label_zh": "LIKE 模糊召回上限",
        "desc_en": "Fallback fuzzy-match candidate cap used when higher-quality recall degrades.",
        "desc_zh": "高质量召回降级时，LIKE 模糊匹配的候选上限。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "superseded_limit",
        "type": "int",
        "default": 20,
        "env": "MEMORY_ARBITER_SUPERSEDED_LIMIT",
        "group": "retrieval",
        "label_en": "Expired page size",
        "label_zh": "过期记忆分页大小",
        "desc_en": "Default page size for expired/superseded recall.",
        "desc_zh": "查询过期、已废弃记忆时的默认分页大小。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "vec.enabled",
        "settings_attr": "enable_sqlite_vec",
        "type": "bool",
        "default": False,
        "env": "MEMORY_ARBITER_ENABLE_SQLITE_VEC",
        "group": "vector_embedding",
        "label_en": "sqlite-vec enabled",
        "label_zh": "启用 sqlite-vec",
        "desc_en": "Enables local vector recall when sqlite-vec and a compatible embedding model are available.",
        "desc_zh": "在 sqlite-vec 和兼容 embedding 模型可用时启用本地向量召回。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "vec.dim",
        "settings_attr": "vec_dim",
        "type": "int",
        "default": 768,
        "env": "MEMORY_ARBITER_VEC_DIM",
        "group": "vector_embedding",
        "label_en": "Vector dimension",
        "label_zh": "向量维度",
        "desc_en": "Vector dimension for the embedding space. Changing it requires a vector rebuild.",
        "desc_zh": "embedding 空间的向量维度，修改后需要重建向量。",
        "risk": "high",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "embedding.provider",
        "settings_attr": "embedding_provider",
        "type": "str",
        "default": None,
        "env": "MEMORY_ARBITER_EMBEDDING_PROVIDER",
        "group": "vector_embedding",
        "label_en": "Embedding provider",
        "label_zh": "Embedding 提供方",
        "desc_en": "Currently supports local GGUF embeddings.",
        "desc_zh": "当前支持本地 GGUF embedding。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "embedding.model_path",
        "settings_attr": "embedding_model_path",
        "type": "path",
        "default": None,
        "env": "MEMORY_ARBITER_EMBEDDING_MODEL_PATH",
        "group": "vector_embedding",
        "label_en": "Embedding model path",
        "label_zh": "Embedding 模型路径",
        "desc_en": "Local GGUF embedding model path used for semantic recall.",
        "desc_zh": "用于语义召回的本地 GGUF embedding 模型路径。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "embedding.auto_query",
        "settings_attr": "embedding_auto_query",
        "type": "bool",
        "default": True,
        "env": "MEMORY_ARBITER_EMBEDDING_AUTO_QUERY",
        "group": "vector_embedding",
        "label_en": "Auto-vectorize queries",
        "label_zh": "自动向量化查询",
        "desc_en": "Vectorizes search queries automatically when semantic recall is configured.",
        "desc_zh": "配置语义召回后，自动对搜索 query 做向量化。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "embedding.auto_write",
        "settings_attr": "embedding_auto_write",
        "type": "bool",
        "default": True,
        "env": "MEMORY_ARBITER_EMBEDDING_AUTO_WRITE",
        "group": "vector_embedding",
        "label_en": "Auto-vectorize writes",
        "label_zh": "自动向量化写入",
        "desc_en": "Stores vectors for new memories when semantic recall is configured.",
        "desc_zh": "配置语义召回后，为新写入记忆自动存储向量。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "embedding.n_ctx",
        "settings_attr": "embedding_n_ctx",
        "type": "int",
        "default": 2048,
        "env": "MEMORY_ARBITER_EMBEDDING_N_CTX",
        "group": "vector_embedding",
        "label_en": "Embedding context",
        "label_zh": "Embedding 上下文",
        "desc_en": "Context window used by the local embedding model.",
        "desc_zh": "本地 embedding 模型使用的上下文窗口。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "embedding.reserved_tokens",
        "settings_attr": "embedding_reserved_tokens",
        "type": "int",
        "default": 64,
        "env": "MEMORY_ARBITER_EMBEDDING_RESERVED_TOKENS",
        "group": "vector_embedding",
        "label_en": "Reserved tokens",
        "label_zh": "预留 token",
        "desc_en": "Token budget reserved around embedding inputs.",
        "desc_zh": "embedding 输入周边预留的 token 预算。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "structured_claim_mode",
        "type": "enum",
        "default": "beta_all",
        "env": "MEMORY_ARBITER_STRUCTURED_CLAIM_MODE",
        "group": "claims",
        "label_en": "Structured claim mode",
        "label_zh": "结构化 claim 模式",
        "desc_en": "Controls the real-time deterministic claim conflict gate.",
        "desc_zh": "控制实时确定性 claim 冲突门禁。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "isolation",
        "type": "enum",
        "default": "none",
        "env": "MEMORY_ARBITER_ISOLATION",
        "group": "workspace",
        "label_en": "Workspace isolation",
        "label_zh": "工作区隔离等级",
        "desc_en": "none, weak, or strict workspace recall behavior.",
        "desc_zh": "控制 none、weak、strict 三档工作区召回行为。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "workspace_match_distance",
        "type": "float",
        "default": 0.25,
        "env": "MEMORY_ARBITER_WORKSPACE_MATCH_DISTANCE",
        "group": "workspace",
        "label_en": "Workspace match distance",
        "label_zh": "工作区匹配距离",
        "desc_en": "Cosine-distance cutoff for workspace alias canonicalization.",
        "desc_zh": "工作区别名归一的 cosine-distance 阈值。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "split.threshold",
        "settings_attr": "split_threshold",
        "type": "int",
        "default": 4000,
        "env": "MEMORY_ARBITER_SPLIT_THRESHOLD",
        "group": "split",
        "label_en": "Split threshold",
        "label_zh": "分段阈值",
        "desc_en": "Minimum content length before long-content section splitting is considered.",
        "desc_zh": "长文进入 section split 判定的最小正文长度。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "split.section_vec_distance_threshold",
        "settings_attr": "section_vec_distance_threshold",
        "type": "float",
        "default": 0.42,
        "env": "MEMORY_ARBITER_SECTION_VEC_DISTANCE_THRESHOLD",
        "group": "split",
        "label_en": "Section vector threshold",
        "label_zh": "分段向量阈值",
        "desc_en": "Distance threshold for section-level vector matches.",
        "desc_zh": "section 级向量命中的距离阈值。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "split.section_fulltext_threshold",
        "settings_attr": "section_fulltext_threshold",
        "type": "float",
        "default": 0.8,
        "env": "MEMORY_ARBITER_SECTION_FULLTEXT_THRESHOLD",
        "group": "split",
        "label_en": "Full-memory threshold",
        "label_zh": "全文返回阈值",
        "desc_en": "When enough sections match, return the full memory instead of fragmented sections.",
        "desc_zh": "命中 section 比例足够高时返回全文，而不是碎片化 section。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "split.max_sections",
        "settings_attr": "max_sections",
        "type": "int",
        "default": 50,
        "env": "MEMORY_ARBITER_MAX_SECTIONS",
        "group": "split",
        "label_en": "Max sections",
        "label_zh": "最大分段数",
        "desc_en": "Maximum number of sections created for one long memory.",
        "desc_zh": "单条长记忆最多创建的 section 数。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "split.max_section_chars",
        "settings_attr": "max_section_chars",
        "type": "int",
        "default": 3600,
        "env": "MEMORY_ARBITER_MAX_SECTION_CHARS",
        "group": "split",
        "label_en": "Max section chars",
        "label_zh": "单段最大字符数",
        "desc_en": "Maximum character length for one section.",
        "desc_zh": "单个 section 的最大字符长度。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "update_check.enabled",
        "settings_attr": "update_check_enabled",
        "type": "bool",
        "default": True,
        "env": None,
        "group": "update",
        "label_en": "Update check",
        "label_zh": "更新检查",
        "desc_en": "Enables optional package update checks.",
        "desc_zh": "启用可选的包版本更新检查。",
        "risk": "safe",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "client",
        "type": "str",
        "default": "codex",
        "env": "MEMORY_ARBITER_CLIENT",
        "group": "client_identity",
        "label_en": "Client",
        "label_zh": "客户端",
        "desc_en": "Client identity; usually set per MCP client environment.",
        "desc_zh": "客户端身份，建议放在各 MCP client 的环境变量中。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "agent_id",
        "type": "str",
        "default": "default",
        "env": "MEMORY_ARBITER_AGENT_ID",
        "group": "client_identity",
        "label_en": "Agent ID",
        "label_zh": "Agent ID",
        "desc_en": "Agent identity; usually set per MCP client environment.",
        "desc_zh": "Agent 身份，建议放在各 MCP client 的环境变量中。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
    {
        "path": "workspace",
        "type": "str",
        "default": "default",
        "env": "MEMORY_ARBITER_WORKSPACE",
        "group": "client_identity",
        "label_en": "Workspace",
        "label_zh": "工作区",
        "desc_en": "Default workspace identity; ordinary writes should pass the active project workspace.",
        "desc_zh": "默认工作区身份；日常写入应传入当前项目工作区。",
        "risk": "caution",
        "editable": False,
        "restart_required": True,
    },
]


def grouped_descriptors() -> list[dict[str, Any]]:
    grouped: list[dict[str, Any]] = []
    for group in GROUPS:
        items = [d for d in CONFIG_DESCRIPTORS if d.get("group") == group["key"]]
        grouped.append({**group, "items": items})
    return grouped
