from __future__ import annotations

INDEX_HTML = """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>mema Console</title>
  <style>
    :root {
      --bg: #f6f9fc; --bg-2: #edf5fb; --card: rgba(255, 255, 255, 0.82); --card-strong: #ffffff;
      --text: #172033; --muted: #64748b; --subtle: #94a3b8; --line: rgba(148, 163, 184, 0.22);
      --blue: #377cf6; --blue-2: #65a7ff; --cyan: #26c6da; --mint: #30c48d; --amber: #f3a634;
      --rose: #ef6678; --purple: #7c6df0; --shadow: 0 18px 45px rgba(31, 61, 112, 0.10);
      --soft-shadow: 0 12px 28px rgba(31, 61, 112, 0.07); --radius: 22px; --radius-sm: 14px;
      font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, \"SF Pro Display\", \"Segoe UI\", \"PingFang SC\", \"Microsoft YaHei\", sans-serif;
    }
    * { box-sizing: border-box; }
    body { margin: 0; color: var(--text); background: radial-gradient(circle at 16% 10%, rgba(55,124,246,.14), transparent 34%), radial-gradient(circle at 85% 18%, rgba(38,198,218,.15), transparent 30%), linear-gradient(135deg, #f8fbff 0%, var(--bg) 48%, #eef7f5 100%); min-height: 100vh; overflow-x: hidden; }
    body::before { content: \"\"; position: fixed; inset: 0; pointer-events: none; opacity: .36; background-image: linear-gradient(rgba(55, 124, 246, .08) 1px, transparent 1px), linear-gradient(90deg, rgba(55, 124, 246, .08) 1px, transparent 1px); background-size: 42px 42px; mask-image: linear-gradient(to bottom, black, transparent 72%); }
    .app { width: min(1480px, calc(100vw - 36px)); margin: 18px auto 30px; position: relative; }
    .topbar, .sidebar, .card, .hero-card, .trust-panel, .dbbar { border: 1px solid var(--line); background: rgba(255,255,255,.72); backdrop-filter: blur(16px); box-shadow: var(--soft-shadow); }
    .topbar { display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 16px 18px; border-radius: 28px; }
    .brand { display: flex; align-items: center; gap: 14px; min-width: 280px; }
    .logo { width: 48px; height: 48px; border-radius: 16px; background: linear-gradient(135deg, #387bf6, #28c7b7); display: grid; place-items: center; color: white; font-weight: 900; letter-spacing: -.04em; box-shadow: 0 14px 30px rgba(55,124,246,.26); position: relative; }
    .logo::after { content: \"\"; width: 18px; height: 18px; border: 2px solid rgba(255,255,255,.72); border-radius: 50%; position: absolute; right: 8px; bottom: 8px; }
    .brand h1 { margin: 0; font-size: 22px; letter-spacing: -.02em; }
    .brand p { margin: 4px 0 0; color: var(--muted); font-size: 13px; }
    .top-actions { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; justify-content: flex-end; }
    .pill, .chip, .mini, .id-badge, .conflict-tag, .status-badge { display: inline-flex; align-items: center; gap: 8px; border-radius: 999px; white-space: nowrap; }
    .pill { padding: 9px 12px; border: 1px solid var(--line); background: rgba(255,255,255,.76); color: var(--muted); font-size: 13px; font-weight: 700; }
    .dot { width: 8px; height: 8px; border-radius: 50%; background: var(--mint); box-shadow: 0 0 0 5px rgba(48,196,141,.12); }
    .lang-toggle { border: 1px solid rgba(55,124,246,.16); background: rgba(255,255,255,.74); border-radius: 999px; padding: 4px; display: flex; gap: 2px; }
    .lang-toggle button { border: 0; background: transparent; border-radius: 999px; padding: 7px 10px; font-weight: 800; color: var(--muted); cursor: pointer; }
    .lang-toggle button.active { background: white; color: var(--blue); box-shadow: 0 5px 14px rgba(31,61,112,.08); }
    .shell { display: grid; grid-template-columns: 252px minmax(0, 1fr); gap: 18px; margin-top: 18px; align-items: start; }
    .sidebar { position: sticky; top: 18px; min-height: calc(100vh - 126px); border-radius: 28px; padding: 16px; display: flex; flex-direction: column; gap: 18px; }
    .sidebar-title { font-size: 12px; color: var(--subtle); text-transform: uppercase; font-weight: 900; letter-spacing: .09em; margin: 3px 6px 0; }
    .sidebar-nav { display: grid; gap: 7px; }
    .side-link { width: 100%; border: 0; background: transparent; padding: 12px 13px; border-radius: 15px; color: #52627a; font-weight: 800; display: flex; align-items: center; justify-content: space-between; cursor: pointer; text-align: left; }
    .side-link.active { background: white; color: var(--blue); box-shadow: 0 7px 16px rgba(31,61,112,.08); }
    .side-meta { margin-top: auto; display: grid; gap: 9px; }
    .side-stat { padding: 11px 12px; border-radius: 17px; background: rgba(255,255,255,.58); border: 1px solid rgba(148,163,184,.16); }
    .side-stat small { display: block; color: var(--subtle); font-weight: 800; margin-bottom: 5px; }
    .side-stat code, code { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; background: rgba(15,23,42,.05); padding: 2px 6px; border-radius: 6px; color: #334155; overflow-wrap: anywhere; }
    .main { min-width: 0; }
    .hero { display: grid; grid-template-columns: 1.25fr .75fr; gap: 18px; }
    .hero-card { min-height: 210px; padding: 26px; border-radius: 30px; background: linear-gradient(135deg, rgba(255,255,255,.86), rgba(247,252,255,.7)); overflow: hidden; position: relative; }
    .hero-card::after { content: \"\"; position: absolute; right: -80px; top: -90px; width: 260px; height: 260px; background: radial-gradient(circle, rgba(38,198,218,.23), transparent 62%); border-radius: 50%; }
    .eyebrow { color: var(--blue); font-weight: 900; font-size: 13px; letter-spacing: .08em; text-transform: uppercase; }
    .hero h2 { margin: 12px 0 12px; font-size: 34px; line-height: 1.12; letter-spacing: -.045em; max-width: 780px; }
    .hero h2 span { color: var(--blue); }
    .hero-copy { color: var(--muted); font-size: 15px; line-height: 1.7; max-width: 850px; }
    .hero-meta { margin-top: 22px; display: flex; gap: 10px; flex-wrap: wrap; }
    .chip { padding: 8px 11px; font-size: 13px; font-weight: 800; background: #eef6ff; color: #2860bd; border: 1px solid rgba(55,124,246,.16); }
    .trust-panel { padding: 22px; border-radius: 30px; border-color: rgba(38,198,218,.18); background: linear-gradient(160deg, rgba(242,251,252,.86), rgba(255,255,255,.78)); }
    .panel-title, .card-head, .pane-top { display: flex; align-items: start; justify-content: space-between; gap: 12px; }
    .panel-title { align-items: center; margin-bottom: 16px; }
    .panel-title h3, .card h3 { margin: 0; font-size: 18px; letter-spacing: -.025em; }
    .status-badge { padding: 7px 10px; background: rgba(48,196,141,.11); color: #16845c; font-weight: 900; font-size: 12px; }
    .status-badge.warn { background: rgba(243,166,52,.13); color: #a46412; }
    .trust-list, .doctor-list, .activity, .conflict-list { display: grid; gap: 10px; }
    .trust-item { display: grid; grid-template-columns: 38px 1fr auto; gap: 10px; align-items: center; padding: 12px; border-radius: 18px; background: rgba(255,255,255,.66); border: 1px solid rgba(148,163,184,.16); }
    .ico { width: 38px; height: 38px; border-radius: 14px; display: grid; place-items: center; color: white; font-weight: 900; }
    .i-blue { background: linear-gradient(135deg, var(--blue), var(--blue-2)); } .i-mint { background: linear-gradient(135deg, var(--mint), #65d9b0); } .i-amber { background: linear-gradient(135deg, var(--amber), #f7ca73); }
    .trust-item strong { display:block; font-size: 14px; } .trust-item small { color: var(--muted); font-size: 12px; } .trust-num { font-weight: 900; color: var(--text); }
    .grid { display: grid; grid-template-columns: 1.05fr .95fr; gap: 18px; margin-top: 18px; }
    .side-grid { display: grid; gap: 18px; }
    .card { border-radius: var(--radius); background: var(--card); overflow: hidden; }
    .card-head { padding: 18px 20px 0; }
    .card .desc { color: var(--muted); margin: 6px 0 0; font-size: 13px; }
    .card-body { padding: 18px 20px 20px; }
    .metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
    .metric { border-radius: 20px; background: rgba(255,255,255,.72); border: 1px solid rgba(148,163,184,.16); padding: 16px; min-height: 118px; position: relative; overflow: hidden; }
    .metric::after { content:\"\"; position:absolute; right:-26px; bottom:-26px; width:78px; height:78px; border-radius: 50%; background: rgba(55,124,246,.08); }
    .metric small { color: var(--muted); font-weight: 800; } .metric b { display:block; margin-top: 10px; font-size: 28px; letter-spacing: -.04em; } .metric span { display:block; margin-top: 4px; color: var(--subtle); font-size: 12px; }
    .conflict-row { display: grid; grid-template-columns: auto 1fr auto; gap: 12px; align-items: center; padding: 14px; border-radius: 18px; background: rgba(255,255,255,.68); border: 1px solid rgba(148,163,184,.16); cursor: pointer; }
    .severity { width: 10px; height: 54px; border-radius: 999px; background: var(--amber); box-shadow: 0 0 0 5px rgba(243,166,52,.09); } .severity.high { background: var(--rose); box-shadow: 0 0 0 5px rgba(239,102,120,.10); } .severity.low { background: var(--mint); box-shadow: 0 0 0 5px rgba(48,196,141,.10); }
    .conflict-main strong { display: block; font-size: 14px; margin-bottom: 4px; } .conflict-main p { margin: 0; color: var(--muted); font-size: 13px; line-height: 1.45; }
    .conflict-tag { padding: 7px 10px; font-size: 12px; font-weight: 900; background: #fff7e8; color: #a46412; border: 1px solid rgba(243,166,52,.18); }
    .split { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .memory-pane { background: rgba(255,255,255,.66); border: 1px solid rgba(148,163,184,.16); border-radius: 20px; padding: 16px; min-height: 265px; }
    .pane-top h4 { margin:0; font-size: 15px; }.id-badge { font-size: 12px; color: var(--muted); background:#f1f5f9; padding: 6px 8px; font-weight: 800; }
    .meta-line { display:flex; flex-wrap:wrap; gap: 7px; margin-bottom: 12px; }.mini { padding: 6px 8px; font-size: 12px; background: #f3f7fb; color: #52627a; font-weight: 800; }.mini.confirmed { background: rgba(48,196,141,.1); color: #16845c; }.mini.agent { background: rgba(124,109,240,.1); color: #6254cd; }
    .memory-text { color: #334155; font-size: 13px; line-height: 1.65; border-top: 1px dashed rgba(148,163,184,.32); padding-top: 12px; max-height: 520px; overflow: auto; white-space: pre-wrap; }
    mark { background: rgba(243,166,52,.22); color: #8a560f; padding: 0 3px; border-radius: 5px; }
    .callout { border-radius: 20px; padding: 15px; margin-bottom: 12px; background: linear-gradient(135deg, rgba(255,247,232,.82), rgba(255,255,255,.68)); border: 1px solid rgba(243,166,52,.22); display: flex; gap: 12px; align-items: start; }
    .callout-icon { width: 32px; height:32px; border-radius: 12px; display:grid; place-items:center; background: var(--amber); color:white; font-weight:900; flex: 0 0 auto; }
    .callout strong { display:block; font-size: 14px; margin-bottom: 5px; } .callout p { margin:0; color: var(--muted); font-size: 13px; line-height: 1.5; }
    .doctor-item { display:flex; align-items:center; justify-content:space-between; padding: 12px 13px; border-radius: 16px; background: rgba(255,255,255,.66); border: 1px solid rgba(148,163,184,.16); gap: 14px; }
    .doctor-item span { color: var(--muted); font-size: 13px; }.pass { color: #16845c; font-weight: 900; }.warn { color: #a46412; font-weight: 900; }.error { color: #b42334; font-weight: 900; }
    .act { display:flex; gap: 11px; align-items: start; }.act-dot { margin-top: 5px; width: 9px; height: 9px; border-radius:50%; background: var(--blue); box-shadow: 0 0 0 5px rgba(55,124,246,.10); flex:0 0 auto; }.act strong { display:block; font-size: 13px; }.act small { color: var(--muted); }
    .dbbar { margin-top: 18px; padding: 14px 18px; border-radius: 20px; color: var(--muted); font-size: 13px; display:flex; justify-content:space-between; gap:12px; }
    .toolbar { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 14px; }.toolbar input, .toolbar select, .toolbar textarea { border: 1px solid var(--line); border-radius: 13px; padding: 10px 12px; background: rgba(255,255,255,.75); color: var(--text); min-width: 160px; }.toolbar textarea { min-height: 84px; width: 100%; resize: vertical; }.toolbar button, .support-btn { border: 0; border-radius: 13px; padding: 10px 13px; color: white; background: linear-gradient(135deg, #2f76f5, #26c1d2); font-weight: 900; cursor: pointer; }.support-actions { display:flex; gap:10px; flex-wrap:wrap; margin-top:14px; }.support-btn.secondary { color: var(--blue); background: rgba(55,124,246,.10); border: 1px solid rgba(55,124,246,.16); }.modal-backdrop { position: fixed; inset: 0; background: rgba(15,23,42,.28); backdrop-filter: blur(8px); display: grid; place-items: center; z-index: 20; padding: 18px; }.modal { width: min(760px, 100%); max-height: calc(100vh - 36px); overflow:auto; border-radius: 26px; background: rgba(255,255,255,.96); border: 1px solid var(--line); box-shadow: var(--shadow); padding: 20px; }.modal h3 { margin: 0 0 8px; }.modal p { color: var(--muted); line-height: 1.55; }.form-grid { display:grid; gap:10px; }.form-grid label { display:grid; gap:5px; font-weight:800; color:#334155; font-size:13px; }.check-row { display:flex; gap:9px; align-items:flex-start; color:var(--muted); font-size:13px; }
    .table-list { display: grid; gap: 9px; }.list-row { padding: 13px 14px; border-radius: 16px; background: rgba(255,255,255,.66); border: 1px solid rgba(148,163,184,.16); cursor: pointer; }.list-row strong { display: block; margin-bottom: 5px; }.list-row small { color: var(--muted); }
    .page-size { display: inline-flex; align-items: center; gap: 6px; font-size: 13px; color: var(--muted); font-weight: 700; }.page-size select { border: 1px solid var(--line); border-radius: 10px; padding: 8px 10px; background: rgba(255,255,255,.75); color: var(--text); min-width: 64px; }
    .pager { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin-top: 16px; padding-top: 12px; border-top: 1px solid rgba(148,163,184,.16); }.pager-info { font-size: 13px; color: var(--muted); }.pager-info .empty { padding: 0; border: 0; background: transparent; color: var(--amber, #a46412); }.pager-btns { display: flex; align-items: center; gap: 10px; }.pager-btns span { font-weight: 800; color: var(--text); min-width: 24px; text-align: center; }.pager-btns button:disabled { opacity: .4; cursor: not-allowed; }.pager-btns .jump { display: inline-flex; align-items: center; gap: 5px; font-size: 13px; color: var(--muted); font-weight: 700; margin-left: 6px; }.pager-btns .jump input { width: 54px; border: 1px solid var(--line); border-radius: 8px; padding: 6px 8px; background: rgba(255,255,255,.75); color: var(--text); text-align: center; }
    .settings-grid { display: grid; gap: 14px; }.config-row { display: grid; grid-template-columns: minmax(180px, 1.2fr) minmax(140px, .8fr) minmax(140px, .8fr) minmax(150px, .8fr); gap: 10px; padding: 13px; border-radius: 16px; background: rgba(255,255,255,.66); border: 1px solid rgba(148,163,184,.16); align-items: start; }.config-row small { display: block; color: var(--muted); margin-top: 4px; line-height: 1.45; }.risk-high { color: #b42334; }.risk-caution { color: #a46412; }.empty { color: var(--muted); padding: 18px; border-radius: 18px; background: rgba(255,255,255,.58); border: 1px dashed rgba(148,163,184,.32); }
    @media (max-width: 1180px) { .shell { grid-template-columns: 1fr; } .sidebar { position: relative; min-height: auto; } .sidebar-nav { grid-template-columns: repeat(5, minmax(120px, 1fr)); overflow-x: auto; } .side-meta { grid-template-columns: repeat(4, minmax(140px, 1fr)); overflow-x: auto; } .hero, .grid { grid-template-columns: 1fr; } .metrics { grid-template-columns: repeat(2, 1fr); } }
    @media (max-width: 720px) { .app { width: min(100vw - 20px, 1480px); margin-top: 10px; } .topbar { align-items: flex-start; flex-direction: column; } .metrics, .split, .config-row { grid-template-columns: 1fr; } .hero h2 { font-size: 27px; } .dbbar { flex-direction: column; } }
  </style>
</head>
<body>
  <main class=\"app\">
    <header class=\"topbar\">
      <section class=\"brand\"><div class=\"logo\">MA</div><div><h1 id=\"brandTitle\">mema Console</h1><p id=\"brandSubtitle\">Local fact governance console</p></div></section>
      <section class=\"top-actions\"><button class=\"support-btn secondary\" type=\"button\" onclick=\"openStar()\">★ <span data-i18n=\"star\">Star</span></button><button class=\"support-btn\" type=\"button\" onclick=\"openFeedback('feature')\" data-i18n=\"feedback\">Feedback</button><span class=\"pill\"><i class=\"dot\"></i><span data-i18n=\"localOnly\">Local only</span></span><span class=\"pill\" data-i18n=\"readOnly\">Read-only</span><span class=\"pill\" id=\"versionPill\">v…</span><div class=\"lang-toggle\"><button id=\"langZh\" type=\"button\">中文</button><button id=\"langEn\" type=\"button\">English</button></div></section>
    </header>
    <section class=\"shell\"><aside class=\"sidebar\"><div><div class=\"sidebar-title\" data-i18n=\"navigation\">Navigation</div><nav class=\"sidebar-nav\" id=\"sidebarNav\"></nav></div><div class=\"side-meta\" id=\"sideMeta\"></div></aside><section class=\"main\" id=\"view\"><div class=\"empty\">Loading…</div></section></section>
  </main>
<script>
const I18N = {
  en: { localOnly:'Local only', readOnly:'Read-only', star:'Star', feedback:'Feedback', supportTitle:'Support mema', supportCopy:'If mema helped, a GitHub star helps others find it. Found a rough edge or have a workflow idea? Send feedback.', starOnGithub:'Star on GitHub', requestFeature:'Request feature', reportBug:'Report bug', uxFeedback:'UX feedback', feedbackPrivacy:'Feedback opens GitHub with a prefilled public issue. Console does not upload your memory automatically.', navigation:'Navigation', overview:'Overview', conflicts:'Conflicts', memories:'Memories', doctor:'Doctor', settings:'Settings', subtitle:'Local fact governance console', heroTitle:'Shared memory is easy. Trustworthy shared memory is hard.', heroCopy:'Agents use remember / find / read every day. Humans use mema Console to inspect health, review conflicts, and build trust. This is not a memory editor; it is a local fact governance console.', sourceTrust:'Source trust', conflictReview:'Conflict review', versionHistory:'Version history', doctorDiagnostics:'Doctor diagnostics', factHealth:'Fact health', totalMemories:'Total memories', active:'Active', expired:'Expired', openConflicts:'Unresolved conflicts', userConfirmed:'User-confirmed facts', availableRecall:'Ready for agent recall', reviewQueue:'Need human review', overviewDesc:'A quick, calm snapshot of your local memory store.', acrossWorkspaces:'Across workspaces', availableForRecall:'Available for recall', historical:'Superseded / historical', reviewQueueTitle:'Conflict review queue', reviewQueueDesc:'Make contradictions visible before they pollute the next answer.', conflictDetail:'Conflict detail', conflictDetailDesc:'The core Arbiter moment: conflict point + all member memories side by side.', conflictPoint:'Conflict point', doctorDesc:'Read-only diagnostics, grouped by dimension.', workspaceDistribution:'Workspace distribution', workspaceDesc:'Lightweight visibility before search telemetry.', recentActivity:'Recent activity', recentDesc:'Only real scan, doctor, and configuration signals are shown.', dbPath:'DB path', noConflicts:'No open conflicts. The conflict table is clean.', noActivity:'No recent activity yet. The MVP does not record search telemetry.', search:'Search', status:'Status', sourceType:'Source type', workspace:'Workspace', tags:'Tags', runSearch:'Search', settingsDesc:'Current effective configuration. Read-only in this version.', configFile:'Config file', exists:'Exists', warnings:'Warnings', current:'Current', defaultValue:'Default', env:'Env fallback', risk:'Risk', restart:'Restart', memoryDetail:'Memory detail', back:'Back', pageSize:'Page size', prev:'Prev', next:'Next', pageOf:'rows on this page', noMoreMatch:'No more matches on this page (deep recall may be exhausted)', total:'total', approx:'~ approx', rows:'rows', jumpTo:'Jump to', page:'Page', pageOfTotal:'of' },
  zh: { localOnly:'仅本地', readOnly:'只读', star:'点星', feedback:'反馈', supportTitle:'支持迷码', supportCopy:'如果迷码帮到了你，点个 Star 能让更多人找到它。遇到卡点或有工作流想法？欢迎反馈。', starOnGithub:'去 GitHub 点星', requestFeature:'提需求', reportBug:'反馈问题', uxFeedback:'体验反馈', feedbackPrivacy:'反馈会打开 GitHub 并预填公开 issue。Console 不会自动上传你的记忆内容。', navigation:'导航', overview:'总览', conflicts:'冲突', memories:'记忆', doctor:'体检', settings:'设置', subtitle:'本地可信事实治理控制台', heroTitle:'共享记忆很容易，可信共享记忆很难。', heroCopy:'Agent 日常只用 remember / find / read；人类通过迷码 Console 查看状态、审计冲突、建立信任。这里不是记忆编辑器，而是本地事实治理控制台。', sourceTrust:'来源可信度', conflictReview:'冲突审计', versionHistory:'版本追溯', doctorDiagnostics:'体检诊断', factHealth:'事实健康', totalMemories:'总记忆数', active:'当前可召回', expired:'历史与废弃', openConflicts:'待处理冲突', userConfirmed:'用户确认事实', availableRecall:'可供 agent 召回', reviewQueue:'需要人工审计', overviewDesc:'快速、清爽地查看本地记忆库状态。', acrossWorkspaces:'跨工作区', availableForRecall:'可用于召回', historical:'已废弃 / 历史', reviewQueueTitle:'冲突审计队列', reviewQueueDesc:'让矛盾在污染下一次回答前先被看见。', conflictDetail:'冲突详情', conflictDetailDesc:'Arbiter 的核心时刻：冲突点 + 全部成员记忆对照。', conflictPoint:'冲突点', doctorDesc:'只读诊断，按维度分组展示。', workspaceDistribution:'工作区分布', workspaceDesc:'在真正 search telemetry 之前，先展示轻量可见性。', recentActivity:'最近活动', recentDesc:'只展示真实 scan、doctor 和配置状态。', dbPath:'数据库路径', noConflicts:'当前没有待处理冲突。冲突表是干净的。', noActivity:'暂无最近活动数据。MVP 暂不记录 search telemetry。', search:'搜索', status:'状态', sourceType:'来源类型', workspace:'工作区', tags:'标签', runSearch:'搜索', settingsDesc:'当前生效配置。此版本只读。', configFile:'配置文件', exists:'是否存在', warnings:'告警', current:'当前值', defaultValue:'默认值', env:'环境变量 fallback', risk:'风险', restart:'重启', memoryDetail:'记忆详情', back:'返回', pageSize:'每页条数', prev:'上一页', next:'下一页', pageOf:'条 / 本页', noMoreMatch:'本页无更多匹配（深页召回可能已耗尽）', total:'共', approx:'约', rows:'条', jumpTo:'跳至', page:'第', pageOfTotal:'/' }
};
const DEFAULT_PAGE_SIZE = 10;
const state = { lang: loadLang(), overview: null, conflicts: [], doctor: null, settings: null, memories: [], detail: null, memPage: { offset: 0, limit: DEFAULT_PAGE_SIZE, hasMore: false, reachedEmpty: false, total: 0, totalPrecise: true, totalPages: 1 }, memFilters: null, memReqSeq: 0 };
const ROUTES = ['overview','conflicts','memories','doctor','settings'];
function loadLang(){ const saved=localStorage.getItem('memoryArbiterConsoleLang'); if(saved==='zh'||saved==='en') return saved; return (navigator.language||'').toLowerCase().startsWith('zh')?'zh':'en'; }
function t(k){ return (I18N[state.lang]&&I18N[state.lang][k]) || I18N.en[k] || k; }
function esc(v){ return String(v ?? '').replace(/[&<>\"']/g, s => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[s])); }
function shortPath(p){ if(!p) return '—'; return String(p).replace(/^\\/Users\\/[^/]+/, '~'); }
async function api(path){ const r = await fetch(path); const j = await r.json(); if(!r.ok) throw new Error(j.error || r.statusText); return j; }
function route(){ const h = location.hash.replace(new RegExp('^#/?'), '') || 'overview'; const parts = h.split('/'); return {name: parts[0] || 'overview', id: parts[1]}; }
function setLang(lang){ state.lang=lang; localStorage.setItem('memoryArbiterConsoleLang', lang); render(); }
function navTo(hash){ location.hash = hash; }
async function init(){ document.getElementById('langZh').onclick=()=>setLang('zh'); document.getElementById('langEn').onclick=()=>setLang('en'); window.addEventListener('hashchange', render); try { state.overview = await api('/api/overview'); state.conflicts = (await api('/api/conflicts?status=open&limit=20')).items || []; state.doctor = await api('/api/doctor'); } catch(e) { document.getElementById('view').innerHTML = `<div class=\"empty\">${esc(e.message)}</div>`; return; } render(); }
function render(){ document.documentElement.lang = state.lang === 'zh' ? 'zh-CN' : 'en'; document.title = `${state.lang==='zh'?'迷码':'mema'} Console`; document.getElementById('brandTitle').textContent = `${state.lang==='zh'?'迷码':'mema'} Console`; document.getElementById('brandSubtitle').textContent=t('subtitle'); document.getElementById('versionPill').textContent = `v${state.overview?.version || '…'}`; document.getElementById('langZh').classList.toggle('active', state.lang==='zh'); document.getElementById('langEn').classList.toggle('active', state.lang==='en'); document.querySelectorAll('[data-i18n]').forEach(el => el.textContent = t(el.dataset.i18n)); renderSidebar(); const r=route(); if(!ROUTES.includes(r.name) && r.name!=='conflict' && r.name!=='memory') location.hash='#/overview'; if(r.name==='overview') renderOverview(); else if(r.name==='conflicts') renderConflicts(); else if(r.name==='conflict') renderConflictDetail(r.id); else if(r.name==='memories') renderMemories(); else if(r.name==='memory') renderMemoryDetail(r.id); else if(r.name==='doctor') renderDoctor(); else if(r.name==='settings') renderSettings(); }
function renderSidebar(){ const r=route(); const items=[['overview',t('overview'),'#/overview'],['conflicts',t('conflicts'),'#/conflicts',state.overview?.counts?.open_conflicts],['memories',t('memories'),'#/memories'],['doctor',t('doctor'),'#/doctor',state.overview?.doctor_overall],['settings',t('settings'),'#/settings']]; document.getElementById('sidebarNav').innerHTML = items.map(([key,label,hash,badge])=>`<button class=\"side-link ${r.name===key||r.name===key.slice(0,-1)?'active':''}\" onclick=\"navTo('${hash}')\"><span>${esc(label)}</span>${badge!==undefined&&badge!==null?`<span class=\"id-badge\">${esc(badge)}</span>`:''}</button>`).join(''); document.getElementById('sideMeta').innerHTML = `<div class=\"side-stat\"><small>${t('openConflicts')}</small><strong>${esc(state.overview?.counts?.open_conflicts ?? 0)}</strong></div><div class=\"side-stat\"><small>${t('doctor')}</small><strong>${esc(state.overview?.doctor_overall ?? '—')}</strong></div><div class=\"side-stat\"><small>mema / 迷码</small><strong>v${esc(state.overview?.version ?? '…')}</strong></div>`; }
function renderOverview(){ const c=state.overview?.counts||{}; const ws=Object.entries(state.overview?.by_workspace||{}).sort((a,b)=>b[1]-a[1]).slice(0,3); const source=state.overview?.by_source_type||{}; document.getElementById('view').innerHTML = `<section class=\"hero\"><article class=\"hero-card\"><div class=\"eyebrow\">Trust Console</div><h2>${esc(t('heroTitle')).replace(/(Trustworthy shared memory|可信共享记忆)/, '<span>$1</span>')}</h2><p class=\"hero-copy\">${esc(t('heroCopy'))}</p><div class=\"hero-meta\"><span class=\"chip\">${t('sourceTrust')}</span><span class=\"chip\">${t('conflictReview')}</span><span class=\"chip\">${t('versionHistory')}</span><span class=\"chip\">${t('doctorDiagnostics')}</span></div></article><aside class=\"trust-panel\"><div class=\"panel-title\"><h3>${t('factHealth')}</h3><span class=\"status-badge ${state.overview?.doctor_overall==='pass'?'':'warn'}\">${esc(state.overview?.doctor_overall||'—')}</span></div><div class=\"trust-list\"><div class=\"trust-item\"><div class=\"ico i-blue\">✓</div><div><strong>${t('userConfirmed')}</strong><small>locked</small></div><div class=\"trust-num\">${esc(source.user_confirmed||0)}</div></div><div class=\"trust-item\"><div class=\"ico i-mint\">↻</div><div><strong>${t('active')}</strong><small>${t('availableRecall')}</small></div><div class=\"trust-num\">${esc(c.active||0)}</div></div><div class=\"trust-item\"><div class=\"ico i-amber\">!</div><div><strong>${t('openConflicts')}</strong><small>${t('reviewQueue')}</small></div><div class=\"trust-num\">${esc(c.open_conflicts||0)}</div></div></div></aside></section><section class=\"grid\"><div><article class=\"card\"><div class=\"card-head\"><div><h3>${t('overview')}</h3><p class=\"desc\">${t('overviewDesc')}</p></div><span class=\"pill\">127.0.0.1</span></div><div class=\"card-body\"><div class=\"metrics\">${metric(t('totalMemories'),c.total,t('acrossWorkspaces'))}${metric(t('active'),c.active,t('availableForRecall'))}${metric(t('expired'),c.expired,t('historical'))}${metric(t('openConflicts'),c.open_conflicts,t('reviewQueue'))}</div></div></article>${doctorSummaryCard()}${conflictQueueCard()}${state.conflicts[0]?conflictPreviewCard(state.conflicts[0]):''}</div><aside class=\"side-grid\">${supportCard()}${workspaceCard(ws)}${activityCard()}</aside></section><footer class=\"dbbar\"><span>${t('dbPath')}: <code>${esc(shortPath(state.overview?.db_path))}</code></span><span>${state.lang==='zh'?'Console 仅本地 · 只读 · 用于事实信任审计':'Console is local-only · read-only · made for trust review'}</span></footer>`; }
function metric(label,num,sub){ return `<div class=\"metric\"><small>${esc(label)}</small><b>${esc(num??0)}</b><span>${esc(sub)}</span></div>`; }
function supportUrls(){ return state.overview?.support || {repo_url:'https://github.com/billy12151/memory-arbiter-mcp', new_issue_url:'https://github.com/billy12151/memory-arbiter-mcp/issues/new'}; }
function openStar(){ window.open(supportUrls().repo_url, '_blank', 'noopener,noreferrer'); }
function supportCard(){ return `<article class=\"card\"><div class=\"card-head\"><div><h3>${t('supportTitle')}</h3><p class=\"desc\">${t('supportCopy')}</p></div></div><div class=\"card-body\"><p class=\"desc\">${t('feedbackPrivacy')}</p><div class=\"support-actions\"><button class=\"support-btn secondary\" onclick=\"openStar()\">★ ${t('starOnGithub')}</button><button class=\"support-btn\" onclick=\"openFeedback('feature')\">${t('requestFeature')}</button><button class=\"support-btn secondary\" onclick=\"openFeedback('bug')\">${t('reportBug')}</button><button class=\"support-btn secondary\" onclick=\"openFeedback('ux_feedback')\">${t('uxFeedback')}</button></div></div></article>`; }
function issueTypeLabel(type){ return type==='bug' ? 'Bug report' : type==='ux_feedback' ? 'UX feedback' : 'Feature request'; }
function buildIssueBody(values){ const diag=[]; if(values.version) diag.push(`- mema version: ${state.overview?.version || 'unknown'}`); if(values.route) diag.push(`- Console route: ${location.hash || '#/overview'}`); if(values.doctor) diag.push(`- Doctor overall: ${state.overview?.doctor_overall || 'unknown'}`); if(values.conflicts) diag.push(`- Unresolved conflicts: ${state.overview?.counts?.open_conflicts ?? 0}`); if(values.warnings) diag.push(`- Config warnings: ${(state.overview?.config_warnings||[]).length}`); return `## Type\n${issueTypeLabel(values.type)}\n\n## What I was trying to do\n${values.trying || ''}\n\n## Current pain\n${values.pain || ''}\n\n## Expected behavior\n${values.expected || ''}\n\n## Why this matters\n${values.matters || ''}\n\n## Console context\n${diag.join('\\n') || '- Not included'}\n\n## Privacy\nI understand this issue is public on GitHub. I did not include private memory content unless I typed it above.`; }
function buildIssueUrl(values){ const title=values.title || `[${issueTypeLabel(values.type)}] mema Console feedback`; const url=new URL(supportUrls().new_issue_url); url.searchParams.set('title', title); url.searchParams.set('body', buildIssueBody(values)); const label=values.type==='bug'?'bug':values.type==='ux_feedback'?'ux':'enhancement'; url.searchParams.set('labels', `${label},from-console`); return url.toString(); }
function openFeedback(type){ const zh=state.lang==='zh'; const feedbackType=['bug','feature','ux_feedback'].includes(type)?type:'feature'; const titleKey=feedbackType==='bug'?'reportBug':feedbackType==='ux_feedback'?'uxFeedback':'requestFeature'; document.body.insertAdjacentHTML('beforeend', `<div class=\"modal-backdrop\" id=\"feedbackModal\" onclick=\"if(event.target.id==='feedbackModal')closeFeedback()\"><section class=\"modal\"><div class=\"panel-title\"><h3>${t(titleKey)}</h3><button class=\"support-btn secondary\" onclick=\"closeFeedback()\">${t('back')}</button></div><p>${t('feedbackPrivacy')}</p><form class=\"form-grid\" onsubmit=\"submitFeedback(event)\"><input type=\"hidden\" id=\"fbType\" value=\"${feedbackType}\"><label>${zh?'标题':'Title'}<input id=\"fbTitle\" required placeholder=\"${zh?'一句话概括':'One-line summary'}\"></label><label>${zh?'你原本想完成什么？':'What were you trying to do?'}<textarea id=\"fbTrying\"></textarea></label><label>${zh?'现在遇到什么卡点？':'Current pain'}<textarea id=\"fbPain\"></textarea></label><label>${zh?'期望是什么？':'Expected behavior'}<textarea id=\"fbExpected\"></textarea></label><label>${zh?'为什么这对工作流重要？':'Why this matters'}<textarea id=\"fbMatters\"></textarea></label><label class=\"check-row\"><input id=\"fbVersion\" type=\"checkbox\" checked>mema version</label><label class=\"check-row\"><input id=\"fbRoute\" type=\"checkbox\" checked>Console route</label><label class=\"check-row\"><input id=\"fbDoctor\" type=\"checkbox\" checked>Doctor overall</label><label class=\"check-row\"><input id=\"fbConflicts\" type=\"checkbox\" checked>Open conflict count</label><label class=\"check-row\"><input id=\"fbWarnings\" type=\"checkbox\">Config warning count</label><div class=\"support-actions\"><button class=\"support-btn\" type=\"submit\">${zh?'在 GitHub 创建预填 issue':'Create prefilled GitHub issue'}</button><button class=\"support-btn secondary\" type=\"button\" onclick=\"closeFeedback()\">${t('back')}</button></div></form></section></div>`); }
function closeFeedback(){ document.getElementById('feedbackModal')?.remove(); }
function submitFeedback(event){ event.preventDefault(); const values={type:document.getElementById('fbType').value,title:document.getElementById('fbTitle').value,trying:document.getElementById('fbTrying').value,pain:document.getElementById('fbPain').value,expected:document.getElementById('fbExpected').value,matters:document.getElementById('fbMatters').value,version:document.getElementById('fbVersion').checked,route:document.getElementById('fbRoute').checked,doctor:document.getElementById('fbDoctor').checked,conflicts:document.getElementById('fbConflicts').checked,warnings:document.getElementById('fbWarnings').checked}; window.open(buildIssueUrl(values), '_blank', 'noopener,noreferrer'); closeFeedback(); }
function conflictQueueCard(){ return `<article class=\"card\" style=\"margin-top:18px;\"><div class=\"card-head\"><div><h3>${t('reviewQueueTitle')}</h3><p class=\"desc\">${t('reviewQueueDesc')}</p></div><span class=\"pill\">${state.conflicts.length} open</span></div><div class=\"card-body conflict-list\">${state.conflicts.length?state.conflicts.slice(0,5).map(conflictRow).join(''):`<div class=\"empty\">${t('noConflicts')}</div>`}</div></article>`; }
function resolutionActionText(x){ const zh=state.lang==='zh'; const action=x?.recommended_resolution_action; if(action==='update_or_merge') return zh?'建议更新/合并，不建议整条过期。':'Update or merge; do not expire the whole memory.'; if(action==='use_contextual_guidance') return zh?'按上下文保留两边。':'Keep both and use by context.'; if(action==='supersede_old_memory') return zh?'可考虑过期旧记忆；仍需用户授权。':'Supersede may be appropriate; user authorization is still required.'; return zh?'等待判断具体处理方式。':'Resolution action is not classified yet.'; }
function conflictRow(x){ const p=x.conflict_point||x.subject||x.reason||`#${x.id}`; return `<div class=\"conflict-row\" onclick=\"navTo('#/conflict/${x.id}')\"><div class=\"severity ${x.confidence_hint==='high'?'high':x.confidence_hint==='low'?'low':''}\"></div><div class=\"conflict-main\"><strong>#${esc(x.id)} · ${esc(x.conflict_type||x.status||'conflict')}</strong><p>${esc(p)}</p></div><span class=\"conflict-tag\">${esc(x.conflict_type||x.confidence_hint||'open')}</span></div>`; }
function conflictPreviewCard(x){ return `<article class=\"card\" style=\"margin-top:18px;\"><div class=\"card-head\"><div><h3>${t('conflictDetail')}</h3><p class=\"desc\">${t('conflictDetailDesc')}</p></div></div><div class=\"card-body\"><div class=\"callout\"><div class=\"callout-icon\">!</div><div><strong>${t('conflictPoint')}</strong><p>${esc(x.conflict_point||x.reason||'—')}</p></div></div><button class=\"side-link active\" onclick=\"navTo('#/conflict/${x.id}')\">${t('conflictDetail')} #${esc(x.id)} →</button></div></article>`; }
function doctorSummaryCard(){ const findings=(state.doctor?.findings||[]).slice(0,6); return `<article class=\"card\"><div class=\"card-head\"><div><h3>${t('doctor')}</h3><p class=\"desc\">${t('doctorDesc')}</p></div></div><div class=\"card-body doctor-list\">${findings.length?findings.map(f=>`<div class=\"doctor-item\"><span>${esc(f.title||f.check||f.category||'check')}</span><b class=\"${(f.status==='pass'||f.severity==='info')?'pass':(f.severity==='error'?'error':'warn')}\">${esc(f.status||f.severity||'n/a')}</b></div>`).join(''):`<div class=\"empty\">${esc(state.doctor?.overall||'—')}</div>`}</div></article>`; }
function workspaceCard(ws){ return `<article class=\"card\"><div class=\"card-head\"><div><h3>${t('workspaceDistribution')}</h3><p class=\"desc\">${t('workspaceDesc')}</p></div></div><div class=\"card-body\"><div class=\"trust-list\">${ws.length?ws.map(([name,count],i)=>`<div class=\"trust-item\"><div class=\"ico ${i===0?'i-blue':i===1?'i-mint':'i-amber'}\">${esc(String(name||'?').slice(0,2))}</div><div><strong>${esc(name||'default')}</strong><small>${t('workspace')}</small></div><div class=\"trust-num\">${esc(count)}</div></div>`).join(''):`<div class=\"empty\">—</div>`}</div></div></article>`; }
function activityCard(){ const scan=state.overview?.last_scan; const warnings=state.overview?.config_warnings||[]; return `<article class=\"card\"><div class=\"card-head\"><div><h3>${t('recentActivity')}</h3><p class=\"desc\">${t('recentDesc')}</p></div></div><div class=\"card-body activity\">${scan?`<div class=\"act\"><span class=\"act-dot\"></span><div><strong>Conflict scan completed</strong><small>${esc(scan.ts||scan.completed_at||'')}</small></div></div>`:''}${warnings.slice(0,2).map(w=>`<div class=\"act\"><span class=\"act-dot\" style=\"background:var(--amber)\"></span><div><strong>Config warning</strong><small>${esc(w)}</small></div></div>`).join('')}${!scan&&!warnings.length?`<div class=\"empty\">${t('noActivity')}</div>`:''}</div></article>`; }
function renderConflicts(){ document.getElementById('view').innerHTML=`<article class=\"card\"><div class=\"card-head\"><div><h3>${t('conflicts')}</h3><p class=\"desc\">${t('reviewQueueDesc')}</p></div></div><div class=\"card-body conflict-list\">${state.conflicts.length?state.conflicts.map(conflictRow).join(''):`<div class=\"empty\">${t('noConflicts')}</div>`}</div></article>`; }
function conflictMemberCards(d){ const pins=new Map((d.member_versions||[]).map(x=>[String(x.memory_id),x])); return (d.members||[]).map((item,index)=>{ const m=item.memory||{}; const pin=pins.get(String(m.id))||{}; return memoryPane(`Member ${index+1} · ${pin.normalized_value||pin.value_raw||'—'}`,m); }).join(''); }
function conflictValueGroups(groups){ return (groups||[]).map(g=>`<div class=\"list-row\"><strong>${esc(g.display_value||g.normalized_value||'—')}</strong><small>${esc((g.members||[]).join(', '))}</small></div>`).join('')||'<div class=\"empty\">—</div>'; }
function conflictDecision(c){ return [c.chosen_value,c.decided_by,c.decision_reason].filter(Boolean).join(' · ')||'—'; }
function conflictApplySummary(summary){ const plan=summary?.plan||[]; return plan.map(x=>`${x.memory_id}: ${x.action} (${x.status})`).join(' · ')||'—'; }
async function renderConflictDetail(id){ document.getElementById('view').innerHTML='<div class=\"empty\">Loading…</div>'; try{ const d=await api(`/api/conflicts/${encodeURIComponent(id)}`); const c=d.conflict||{}; document.getElementById('view').innerHTML=`<article class=\"card\"><div class=\"card-head\"><div><h3>${t('conflictDetail')} #${esc(c.id)}</h3><p class=\"desc\">revision ${esc(d.revision??c.revision??'—')} · ${esc(c.status||'—')}</p></div><button class=\"side-link\" onclick=\"navTo('#/conflicts')\">${t('back')}</button></div><div class=\"card-body\"><div class=\"callout\"><div class=\"callout-icon\">!</div><div><strong>${t('conflictPoint')}</strong><p>${esc(c.conflict_point||c.detection_reason||'—')}</p></div></div><div class=\"callout\"><div class=\"callout-icon\">↳</div><div><strong>Decision</strong><p>${esc(conflictDecision(c))}</p><small>Apply: ${esc(conflictApplySummary(d.apply_summary))}</small></div></div><h4>Value groups</h4><div class=\"table-list\">${conflictValueGroups(d.value_groups)}</div><h4>Members (${esc((d.members||[]).length)})</h4><div class=\"split\">${conflictMemberCards(d)}</div></div></article>`;}catch(e){document.getElementById('view').innerHTML=`<div class=\"empty\">${esc(e.message)}</div>`;} }
function memoryPane(title,m){ return `<section class=\"memory-pane\"><div class=\"pane-top\"><h4>${esc(title)}</h4><span class=\"id-badge\">id ${esc(m.id||'—')}</span></div><div class=\"meta-line\"><span class=\"mini ${m.source_type==='user_confirmed'?'confirmed':'agent'}\">${esc(m.source_type||'—')}</span><span class=\"mini\">${esc(m.status||'—')}</span><span class=\"mini\">v${esc(m.version||'—')}</span></div><strong>${esc(m.subject||'')}</strong><div class=\"memory-text\">${esc(m.content||'')}</div></section>`; }
function renderMemories(){ const sizeOpts=[10,20]; if(!state.memFilters){ state.memPage={offset:0,limit:DEFAULT_PAGE_SIZE,hasMore:false,reachedEmpty:false,total:0,totalPrecise:true,totalPages:1}; state.memFilters={query:'',status:'active',sourceType:'',workspace:'',tags:''}; } const f=state.memFilters; document.getElementById('view').innerHTML=`<article class=\"card\"><div class=\"card-head\"><div><h3>${t('memories')}</h3><p class=\"desc\">${t('memoryDetail')}</p></div></div><div class=\"card-body\"><form class=\"toolbar\" onsubmit=\"event.preventDefault(); commitFilters();\"><input id=\"q\" placeholder=\"${t('search')}\" value=\"${esc(f.query)}\"><select id=\"memStatus\"><option value=\"active\" ${f.status==='active'?'selected':''}>active</option><option value=\"expired\" ${f.status==='expired'?'selected':''}>expired</option></select><input id=\"sourceType\" placeholder=\"${t('sourceType')}\" value=\"${esc(f.sourceType)}\"><input id=\"ws\" placeholder=\"${t('workspace')}\" value=\"${esc(f.workspace)}\"><input id=\"tagInput\" placeholder=\"${t('tags')}\" value=\"${esc(f.tags)}\"><label class=\"page-size\">${t('pageSize')} <select id=\"memPageSize\" onchange=\"state.memPage.limit=parseInt(this.value,10)||DEFAULT_PAGE_SIZE; state.memPage.offset=0; state.memPage.reachedEmpty=false; loadMemories();\">${sizeOpts.map(s=>`<option value=\"${s}\" ${s===state.memPage.limit?'selected':''}>${s}</option>`).join('')}</select></label><button>${t('runSearch')}</button></form><div id=\"memoryResults\" class=\"table-list\"></div><div id=\"memoryPager\" class=\"pager\"></div></div></article>`; const ps=document.getElementById('memPageSize'); if(ps){ ps.value=String(state.memPage.limit); } loadMemories().catch(e=>{ const el=document.getElementById('memoryResults'); if(el) el.innerHTML=`<div class=\"empty\">${esc(e.message)}</div>`; }); }
function commitFilters(){ state.memFilters={query:document.getElementById('q')?.value||'',status:document.getElementById('memStatus')?.value||'active',sourceType:document.getElementById('sourceType')?.value||'',workspace:document.getElementById('ws')?.value||'',tags:document.getElementById('tagInput')?.value||''}; state.memPage.offset=0; state.memPage.reachedEmpty=false; loadMemories(); }
async function loadMemories(){ const results=document.getElementById('memoryResults'); const pager=document.getElementById('memoryPager'); const seq=++state.memReqSeq; const f=state.memFilters||{}; try { const params=new URLSearchParams({query:f.query||'',status:f.status||'active',source_type:f.sourceType||'',workspace:f.workspace||'',tags:f.tags||'',limit:String(state.memPage.limit),offset:String(state.memPage.offset)}); const d=await api('/api/memories?'+params.toString()); if(seq!==state.memReqSeq){ return; } state.memPage.hasMore=Boolean(d.has_more); state.memPage.total=Number(d.total||0); state.memPage.totalPrecise=Boolean(d.total_precise!==false); const items=d.items||[]; if(items.length===0 && state.memPage.offset>0 && (state.memPage.hasMore || (d.warnings||[]).length>0)){ state.memPage.reachedEmpty=true; } state.memPage.totalPages=state.memPage.total>0?Math.max(1,Math.ceil(state.memPage.total/state.memPage.limit)):1; results.innerHTML=items.map(m=>`<div class=\"list-row\" onclick=\"navTo('#/memory/${m.id}')\"><strong>#${esc(m.id)} · ${esc(m.subject||'(no subject)')}</strong><small>${esc(m.status||'')} · ${esc(m.source_type||'')} · ${esc(m.workspace||'')}</small></div>`).join('') || '<div class=\"empty\">—</div>'; if(pager){ const hasPrev=state.memPage.offset>0; const hasNext=state.memPage.hasMore && !state.memPage.reachedEmpty; const pageNum=Math.floor(state.memPage.offset/state.memPage.limit)+1; const totalLabel=state.memPage.totalPrecise?`${t('total')} ${state.memPage.total} ${t('rows')}`:`${t('approx')} ${state.memPage.total} ${t('rows')}`; const jumpDisabled=state.memPage.totalPages<=1; pager.innerHTML=`<div class=\"pager-info\"><span>${items.length} ${t('pageOf')} · ${totalLabel}</span>${state.memPage.reachedEmpty?`<span class=\"empty\">${t('noMoreMatch')}</span>`:''}</div><div class=\"pager-btns\"><button class=\"support-btn secondary\" ${hasPrev?'':'disabled'} onclick=\"memPrev()\">${t('prev')}</button><span>${t('page')} ${pageNum} ${t('pageOfTotal')} ${state.memPage.totalPages}${state.memPage.totalPrecise?'':'~'}</span><button class=\"support-btn secondary\" ${hasNext?'':'disabled'} onclick=\"memNext()\">${t('next')}</button><label class=\"jump\">${t('jumpTo')} <input id=\"memJump\" type=\"number\" min=\"1\" max=\"${state.memPage.totalPages}\" value=\"${pageNum}\" ${jumpDisabled?'disabled':''} onkeydown=\"if(event.key==='Enter'){event.preventDefault(); memJump(parseInt(this.value,10)||1);}\"></label></div>`; } } catch(e) { if(seq!==state.memReqSeq){ return; } if(results) results.innerHTML=`<div class=\"empty\">${esc(e.message)}</div>`; if(pager) pager.innerHTML=''; } }
function memPrev(){ state.memPage.offset=Math.max(0,state.memPage.offset-state.memPage.limit); state.memPage.reachedEmpty=false; loadMemories(); }
function memNext(){ state.memPage.offset+=state.memPage.limit; loadMemories(); }
function memJump(page){ const tp=state.memPage.totalPages||1; const cur=Math.floor(state.memPage.offset/state.memPage.limit)+1; const p=Math.max(1,Math.min(page,tp)); if(p===cur){ const ji=document.getElementById('memJump'); if(ji){ ji.value=String(cur); } return; } state.memPage.offset=(p-1)*state.memPage.limit; state.memPage.reachedEmpty=false; loadMemories(); }
async function renderMemoryDetail(id){ document.getElementById('view').innerHTML='<div class=\"empty\">Loading…</div>'; try{ const d=await api(`/api/memories/${encodeURIComponent(id)}`); const m=d.memory||{}; document.getElementById('view').innerHTML=`<article class=\"card\"><div class=\"card-head\"><div><h3>${t('memoryDetail')} #${esc(m.id)}</h3><p class=\"desc\">${esc(m.subject||'')}</p></div><button class=\"side-link\" onclick=\"navTo('#/memories')\">${t('back')}</button></div><div class=\"card-body\">${memoryPane(t('memoryDetail'),m)}</div></article>`;}catch(e){document.getElementById('view').innerHTML=`<div class=\"empty\">${esc(e.message)}</div>`;} }
function renderDoctor(){ const findings=state.doctor?.findings||[]; document.getElementById('view').innerHTML=`<article class=\"card\"><div class=\"card-head\"><div><h3>${t('doctor')}</h3><p class=\"desc\">${t('doctorDesc')}</p></div><span class=\"status-badge ${state.doctor?.overall==='pass'?'':'warn'}\">${esc(state.doctor?.overall||'—')}</span></div><div class=\"card-body doctor-list\">${findings.map(f=>`<div class=\"doctor-item\"><span><strong>${esc(f.title||f.check||f.category||'check')}</strong><br><small>${esc(f.detail||f.fix_hint||'')}</small></span><b class=\"${(f.status==='pass'||f.severity==='info')?'pass':(f.severity==='error'?'error':'warn')}\">${esc(f.status||f.severity||'n/a')}</b></div>`).join('')||'<div class=\"empty\">—</div>'}</div></article>`; }
async function renderSettings(){ document.getElementById('view').innerHTML='<div class=\"empty\">Loading…</div>'; try{ state.settings=state.settings||await api('/api/settings'); const s=state.settings; document.getElementById('view').innerHTML=`<article class=\"card\"><div class=\"card-head\"><div><h3>${t('settings')}</h3><p class=\"desc\">${t('settingsDesc')}</p></div><span class=\"pill\">${state.lang==='zh'?s.message_zh:s.message_en}</span></div><div class=\"card-body settings-grid\"><div class=\"callout\"><div class=\"callout-icon\">i</div><div><strong>${t('configFile')}</strong><p><code>${esc(shortPath(s.config_file?.path))}</code> · ${t('exists')}: ${esc(Boolean(s.config_file?.exists))} · ${t('warnings')}: ${esc((s.config_file?.warnings||[]).length)}</p></div></div>${s.groups.map(group=>`<article class=\"card\"><div class=\"card-head\"><div><h3>${esc(state.lang==='zh'?group.label_zh:group.label_en)}</h3></div></div><div class=\"card-body settings-grid\">${group.items.map(configRow).join('')}</div></article>`).join('')}</div></article>`;}catch(e){document.getElementById('view').innerHTML=`<div class=\"empty\">${esc(e.message)}</div>`;} }
function configRow(x){ const label=state.lang==='zh'?x.label_zh:x.label_en; const desc=state.lang==='zh'?x.desc_zh:x.desc_en; return `<div class=\"config-row\"><div><strong>${esc(label)}</strong><small><code>${esc(x.path)}</code> · ${esc(desc)}</small></div><div><small>${t('current')}</small><code>${esc(x.current ?? '—')}</code></div><div><small>${t('defaultValue')}</small><code>${esc(x.default ?? '—')}</code></div><div><small>${t('env')}</small><code>${esc(x.env ?? '—')}</code><small class=\"risk-${esc(x.risk)}\">${t('risk')}: ${esc(x.risk)} · ${t('restart')}: ${esc(x.restart_required)}</small></div></div>`; }
init();
</script>
</body>
</html>
"""
